// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: helloworld.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Com.Persagy.Grpc {
  public static partial class HelloGRPC
  {
    static readonly string __ServiceName = "com.persagy.grpc.HelloGRPC";

    static readonly grpc::Marshaller<global::Com.Persagy.Grpc.HelloRequest> __Marshaller_com_persagy_grpc_HelloRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Persagy.Grpc.HelloRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Com.Persagy.Grpc.HelloReply> __Marshaller_com_persagy_grpc_HelloReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Com.Persagy.Grpc.HelloReply.Parser.ParseFrom);

    static readonly grpc::Method<global::Com.Persagy.Grpc.HelloRequest, global::Com.Persagy.Grpc.HelloReply> __Method_SayHello = new grpc::Method<global::Com.Persagy.Grpc.HelloRequest, global::Com.Persagy.Grpc.HelloReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "SayHello",
        __Marshaller_com_persagy_grpc_HelloRequest,
        __Marshaller_com_persagy_grpc_HelloReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Com.Persagy.Grpc.HelloworldReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of HelloGRPC</summary>
    public abstract partial class HelloGRPCBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Com.Persagy.Grpc.HelloReply> SayHello(global::Com.Persagy.Grpc.HelloRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for HelloGRPC</summary>
    public partial class HelloGRPCClient : grpc::ClientBase<HelloGRPCClient>
    {
      /// <summary>Creates a new client for HelloGRPC</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public HelloGRPCClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for HelloGRPC that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public HelloGRPCClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected HelloGRPCClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected HelloGRPCClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Com.Persagy.Grpc.HelloReply SayHello(global::Com.Persagy.Grpc.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHello(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Com.Persagy.Grpc.HelloReply SayHello(global::Com.Persagy.Grpc.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_SayHello, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Persagy.Grpc.HelloReply> SayHelloAsync(global::Com.Persagy.Grpc.HelloRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SayHelloAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Com.Persagy.Grpc.HelloReply> SayHelloAsync(global::Com.Persagy.Grpc.HelloRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_SayHello, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override HelloGRPCClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new HelloGRPCClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(HelloGRPCBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_SayHello, serviceImpl.SayHello).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, HelloGRPCBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_SayHello, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Com.Persagy.Grpc.HelloRequest, global::Com.Persagy.Grpc.HelloReply>(serviceImpl.SayHello));
    }

  }
}
#endregion
